### ISSUE TITLE
mpd-api throws UnhandledPromiseRejectionWarning: TypeError on mutatorsList.flat.

### ISSUE THREAD

**Issue by IAMSolaara** [cotko/mpd-api#3]
Hello. I'm using mpd-api in conjunction with express and am starting to make a `/status` GET which gets mpd-api's status and sends it away.
I get this error: `UnhandledPromiseRejectionWarning: TypeError: mutatorsList.flat is not a function` when trying to get the status this way: 
```
app.get('/status', async (req,res)=> {
  const client = await mpdapi.connect(mpdConfig) //mpdConfig has host and port set to 'localhost' and 6600
  const status = await client.api.status.get()
  console.log(status)
  res.send({}); //TODO: actually send stuff
})
```

**Comment by cotko** [comment]
@lorecast162 hmm what version of node are you using? Array.flat was added in node v11, I guess I'll need to add this to package.json here.

**Comment by cotko** [comment]
Min engine was set to 11, if anyone else needs to use old node versions with this module, use [array polyfills ](https://github.com/jonathantneal/array-flat-polyfill#readme)for missing methods.
