### ISSUE TITLE
client.on is not a function

### ISSUE THREAD

**Issue by Doedelpumpe** [cotko/mpd-api#4]
Coding a MPD-Client in NodeJS.
Want to catch changes in the queue to refresh the view in my webApp but can't get 
client.on()
to run. Trying it for days now. Anybody can tell me how to do it ? An example would be awesome :)

Errors like 
`client.on is not a function`
`await only in async functions...`

**Comment by Doedelpumpe** [comment]
mpd-api is based on mpd2. I tried to idle with mpd2 package but it did not work as well.
the solution yet, is to use the "old" mpd package:
https://www.npmjs.com/package/mpd
works now. would be awesome if the newer package(s) with more functions could get this working too :)

**Comment by cotko** [comment]
@Doedelpumpe what exactly are you doing? mpd2 has same functionality as mpd in this sense:

```
const mpdapi = require('mpd-api')
const client = await mpdapi.connect()

// all system events (mixer/player/playlist/...)
client.on('system', which => {
   console.log('got system event: ', which)
})

// specific event only
client.on('system-playlist', () => {
   console.log('current queue change')
})
```

**Comment by Doedelpumpe** [comment]
I am running MPD-Client outside of a function in a Server-Client-NodeJS-React-App. The MPD-Client is running on the Server catching the IDLE and sending msgs via socket.io to clients or starting functions on the server when MPD started a new song like adding the next song to the queue.

```
var mpd = require('mpd'),
    cmd = mpd.cmd
var client = mpd.connect({
    port: mpdconf.port,
    host: mpdconf.host,
});
client.on('ready', function () {
    console.log("MPD is ready");
});
```
this works with mpd but not with mpd2 or mpd-api

**Comment by cotko** [comment]
@Doedelpumpe it doesn't, since _mpd2_ is promise based and _mpd_ is callback based. You're assigning a _promise_ to a client when you do this:
```
var client = mpd2.connect({...})
```

If you want to use mpd-api or mpd2, then you need to adjust to promises. You can either use _await_ or _promise.then()_ 

```
function listenToMpdEvents (client) {
  client.on('system', function (eventName) {
    console.log("got mpd event:", eventName);
  });
}
```

connect to MPD using _await_ (_async_ function)
```
async function connectToMpd () {
 
  try {
    var client = await mpd.connect({ port: mpdconf.port, host: mpdconf.host })

    // MPD is ready here, no need for .on('ready'), if there's a problem, error will be thrown
    listenToMpdEvents(client)
  } catch (err) {
     console.error('mpd connect problem', err)
  }

}

connectToMpd()
```

or you can use promise.then instead:
```
 mpd
   .connect({ port: mpdconf.port, host: mpdconf.host })
   .then(listenToMpdEvents)
   .catch(err => console.error('mpd connect problem', err)

```

You should read about promises here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
